---
- name: Install Security Updates
  # note: This is for the test group only
  hosts: all
  gather_facts: no
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
        security: yes
...
